{% set name = "ssh-python" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssh-python-{{ version }}.tar.gz
  sha256: 68bee3f5a657e657d6dcc94e1b6c9ec332fd5d59bf4976a54150b997a800bf68

build:
  skip: true  # [py<36 or win]
  script: SYSTEM_LIBSSH=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - libssh
    - pip
  run:
    - python

test:
  imports:
    - ssh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ParallelSSH/ssh-python
  summary: libssh C library bindings for Python.
  license: LGPL-2.1-only AND BSD-3-Clause
  license_file:
    - COPYING
    - LICENSE
    - libssh/COPYING
    - libssh/cmake/Modules/COPYING-CMAKE-SCRIPTS

extra:
  recipe-maintainers:
    - thewchan
