{% set name = "ssh-python" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be44618803fcaa1c2cd0298b3fb5f3064220a8b3dd36670ac0cc08efc7ae2aaf

build:
  skip: true  # [py<36 or win]
  script: SYSTEM_LIBSSH=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - libssh
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - ssh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ParallelSSH/ssh-python
  summary: libssh C library bindings for Python.
  license: LGPL-2.1-only AND BSD-3-Clause
  license_file:
    - COPYING
    - LICENSE
    - libssh/COPYING
    - libssh/cmake/Modules/COPYING-CMAKE-SCRIPTS

extra:
  recipe-maintainers:
    - thewchan
